### PR TITLE
prevent configuration file from overriding program

### LINKED ISSUE #966: panic: runtime error: index out of range [-1]
Since https://github.com/nanovms/ops/commit/50a178d73871113ae0950f94e5d3ccc977fc22a8, I am getting:

```sh
# with any config.json, e.g.
$ cat ./config.json
{
  "Dirs" : ["./"]
}

$ ops run ./myApp -c ./config.json
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/nanovms/ops/fs.(*Manifest).AddFileTo(0xc000456b10, 0xc000456ae0, 0xc0000344b8, 0x1, 0x0, 0x0, 0xc0002744e0, 0x1)
        /home/am11/ops/fs/manifest.go:327 +0x7a0
github.com/nanovms/ops/fs.(*Manifest).AddFile(...)
        /home/am11/ops/fs/manifest.go:312
github.com/nanovms/ops/fs.(*Manifest).AddUserProgram(0xc000456b10, 0x0, 0x0)
        /home/am11/ops/fs/manifest.go:58 +0x1c3
github.com/nanovms/ops/lepton.BuildManifest(0xc0006c1650, 0x1acaa6f, 0xc00024a300, 0xc000210700)
        /home/am11/ops/lepton/image.go:309 +0x250
github.com/nanovms/ops/lepton.BuildImage(0x3b32ba8, 0x0, 0x0, 0x0, 0x0, 0xc0000c6ba0, 0x1f, 0x0, 0x0, 0x0, ...)
        /home/am11/ops/lepton/image.go:29 +0x2f
github.com/nanovms/ops/cmd.runCommandHandler(0xc00002a780, 0xc0004564b0, 0x1, 0x3)
        /home/am11/ops/cmd/cmd_run.go:64 +0x499
github.com/spf13/cobra.(*Command).execute(0xc00002a780, 0xc0004563f0, 0x3, 0x3, 0xc00002a780, 0xc0004563f0)
        /home/am11/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000248a00, 0x0, 0x96380, 0xc0000a4058)
        /home/am11/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/am11/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/am11/ops/ops.go:8 +0x27
```

it works fine until previous commit 285a23e8b2c093baec59cd3ac7f2ecb7aa6b3d9e.

### LINKED ISSUE #967: merging configurations override program

### PR DESCRIPTION
**Pull request by fabioDMFerreira**
closes #966 closes #967

### CODE REVIEW

**Review by eyberg — APPROVED** [review]

File: cmd/flags_config.go [hunk 1]
```diff
@@ -35,25 +39,23 @@ func (flags *ConfigCommandFlags) MergeToConfig(c *types.Config) (err error) {
 }
 
 // unWarpConfig parses lepton config file from file
-func unWarpConfig(file string) *types.Config {
-	c := types.Config{}
+func unWarpConfig(file string, c *types.Config) (err error) {
```
Comment (am11) [inline cmd/flags_config.go:42]: nit: typo `unWrapConfig`
